### ISSUE TITLE
Build is not optimized for components

### ISSUE THREAD

**Issue by p0o** [jeremyxgo/react-component-boilerplate#2]
Considering that devs want to use this boilerplate for making components and libraries, using webpack for the final build is not necessary and is making the production file very heavy. The common practice is just to compile the es6 to es5 through babel and let the users use their own bundling preference to bundle the requirements (like react and etc)

I already have the config so if you are okay with the changes I can submit the PR

**Comment by jeremyxgo** [comment]
That sounds good, please submit the PR.

**Comment by jeremyxgo** [comment]
After considering that this is a webpack-base boilerplate, I decide to keep the build script as it is now.
